### ISSUE TITLE
Functions tripping up on geom_sf()?

### ISSUE THREAD

**Issue by jdsher** [thomasp85/ggfx#15]
Very possible I've missed some key understanding, but at first pass it appears that some functions, specifically `as_reference() `and `with_shadow()` do not work with `sf` objects/`geom_sf()`. Looks to be some incompatibility with sf's geometry list columns? I keep getting `Error in UseMethod("with_shadow") : no applicable method for 'with_shadow' applied to an object of class "list"`

Reprex:
```
library(tidyverse)
library(sf)
library(ggfx)

nc <- st_read(system.file("shape/nc.shp", package="sf"))

ggplot(nc) +
  as_reference(
    geom_sf(data = nc,
            aes(fill = BIR79)),
    id = "nc"
)

ggplot(nc) +
  with_shadow(
    geom_sf(aes(fill = BIR79)),
    sigma = 3
)

```

**Comment by thomasp85** [comment]
Thank you for the report - it is an oversight on my part. `geom_sf()` returns a list instead of a layer and I didn't plan for that

**Comment by k-hench** [comment]
I hope it is not impolite to comment on a closed issue :hand_over_mouth: 
Yet, I wanted to give a quick heads up since I regularly use {ggfx} with `geom_sf()` and it works just fine.
I simply catch the first element of said returned list - like so:

``` r
library(rnaturalearth)
library(sf)
library(ggfx)
library(ggplot2)

canada <- ne_states(country = "Canada", returnclass = "sf")

canada_inset <- st_buffer(canada, -.7)

ggplot() +
  as_reference(
    geom_sf(data = canada_inset)[[1]],
    id = 'inset' ) +
  geom_sf(data = canada) +
  with_blend(
    with_blur( geom_sf(data = canada_inset,
                       size = 3,
                       color = rgb(0,0,0,.4), 
                       fill = "transparent")[[1]],
               sigma = 3),
    bg_layer = 'inset',
    blend_type = 'in') +
  coord_sf(crs = 3347)
```

![](https://imgur.com/Z09Qjxk)

(link to the plot on [imgur](https://imgur.com/Z09Qjxk) - I believe it is not displayed on github...)

<sup>Created on 2021-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by thomasp85** [comment]
Not impolite at all. However, the release version of ggfx handles `geom_sf()` just fine so there is no need to jump through any hoops to get it working🙂

**Comment by k-hench** [comment]
awesome - I missed that update :+1:  :star_struck:
